services:
  - type: web
    name: Go-Filter-Bot-v1
    env: go
    buildCommand: go build -o app .
    startCommand: ./app
    plan: free
    region: oregon
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMINS
        sync: false
      - key: PORT
        value: 10000
